config/routes.rb
Rails.application.routes.draw do
resources :users do
  member do
    get :posts
  end
end
  resources :posts

  resources :account_histories
  resources :accounts
  resources :suppliers
  resources :appoinments
  resources :docters do
    member do
      get :appoinments
    end
  end

  resources :patients
  root "appoinments#index"

end

app/models/docter.rb
class Docter < ActiveRecord::Base
  has_many :patients
  #belongs_to :patient
  has_many :appointments,through: :appointments
  validates :name, presence:true
  # scope 'appoinments',->{joins(:appoinments).where(:id => id) }

def self.test
  Docter.update_all(:name => "sirish")
end
end

app/controllers/docters_controller.rb
class DoctersController < ApplicationController
  before_action :set_docter, only: [:show, :edit, :update, :destroy]

  # GET /docters
  # GET /docters.json
  def index
    @docters = Docter.all
  end

  # GET /docters/1
  # GET /docters/1.json
  def show
  end

  # GET /docters/new
  def new
    @docter = Docter.new
  end

  # GET /docters/1/edit
  def edit
  end

  # POST /docters
  # POST /docters.json
  def create
    @docter = Docter.new(docter_params)

    respond_to do |format|
      if @docter.save
        format.html { redirect_to @docter, notice: 'Docter was successfully created.' }
        format.json { render :show, status: :created, location: @docter }
      else
        format.html { render :new }
        format.json { render json: @docter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docters/1
  # PATCH/PUT /docters/1.json
  def update
    respond_to do |format|
      if @docter.update(docter_params)
        format.html { redirect_to @docter, notice: 'Docter was successfully updated.' }
        format.json { render :show, status: :ok, location: @docter }
      else
        format.html { render :edit }
        format.json { render json: @docter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docters/1
  # DELETE /docters/1.json
  def destroy
    @docter.destroy
    respond_to do |format|
      format.html { redirect_to docters_url, notice: 'Docter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def appoinments
    @docter = Docter.find(params[:id])
      @appointments = @docter.appoinments
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_docter
      @docter = Docter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def docter_params
      params.require(:docter).permit(:name, :address)
    end
end

app/helpers/docters_helper.rb
module DoctersHelper
end

app/views/docters/_form.html.erb
<%= simple_form_for(@docter) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/docters/appoinments.html.erb
<% @appoinments.each do |app| %>
  <%= app.inspect %>
<% end %>

app/views/docters/edit.html.erb
<h1>Editing Docter</h1>

<%= render 'form' %>

<%= link_to 'Show', @docter %> |
<%= link_to 'Back', docters_path %>

app/views/docters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Docters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @docters.each do |docter| %>
      <tr>
        <td><%= link_to docter.name,appoinments_docter_path(docter),method: :get %></td>
        <td><%= docter.address %></td>
        <td><%= link_to 'Show', docter %></td>
        <td><%= link_to 'Edit', edit_docter_path(docter) %></td>
        <td><%= link_to 'Destroy', docter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Docter', new_docter_path %>

app/views/docters/new.html.erb
<h1>New Docter</h1>

<%= render 'form' %>

<%= link_to 'Back', docters_path %>

app/views/docters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @docter.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @docter.address %>
</p>

<%= link_to 'Edit', edit_docter_path(@docter) %> |
<%= link_to 'Back', docters_path %>