config/routes.rb
Rails.application.routes.draw do
resources :users do
  member do
    get :posts
  end
end
  resources :posts

  resources :account_histories
  resources :accounts
  resources :suppliers
  resources :appoinments
  resources :docters do
    member do
      get :appoinments
    end
  end

  resources :patients
  root "appoinments#index"

end

app/models/account_history.rb
class AccountHistory < ActiveRecord::Base
  belongs_to :account
end

app/controllers/account_histories_controller.rb
class AccountHistoriesController < ApplicationController
  before_action :set_account_history, only: [:show, :edit, :update, :destroy]

  # GET /account_histories
  # GET /account_histories.json
  def index
    @account_histories = AccountHistory.all
  end

  # GET /account_histories/1
  # GET /account_histories/1.json
  def show
  end

  # GET /account_histories/new
  def new
    @account_history = AccountHistory.new
  end

  # GET /account_histories/1/edit
  def edit
  end

  # POST /account_histories
  # POST /account_histories.json
  def create
    @account_history = AccountHistory.new(account_history_params)

    respond_to do |format|
      if @account_history.save
        format.html { redirect_to @account_history, notice: 'Account history was successfully created.' }
        format.json { render :show, status: :created, location: @account_history }
      else
        format.html { render :new }
        format.json { render json: @account_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account_histories/1
  # PATCH/PUT /account_histories/1.json
  def update
    respond_to do |format|
      if @account_history.update(account_history_params)
        format.html { redirect_to @account_history, notice: 'Account history was successfully updated.' }
        format.json { render :show, status: :ok, location: @account_history }
      else
        format.html { render :edit }
        format.json { render json: @account_history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account_histories/1
  # DELETE /account_histories/1.json
  def destroy
    @account_history.destroy
    respond_to do |format|
      format.html { redirect_to account_histories_url, notice: 'Account history was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account_history
      @account_history = AccountHistory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_history_params
      params.require(:account_history).permit(:account_id, :amount)
    end
end

app/helpers/account_histories_helper.rb
module AccountHistoriesHelper
end

app/views/account_histories/_form.html.erb
<%= simple_form_for(@account_history) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <%= f.collection_select :account_id, Account.all, :id, :name %>
    <%= f.input :amount %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/account_histories/edit.html.erb
<h1>Editing Account History</h1>

<%= render 'form' %>

<%= link_to 'Show', @account_history %> |
<%= link_to 'Back', account_histories_path %>

app/views/account_histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Account Histories</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_histories.each do |account_history| %>
      <tr>
        <td><%= account_history.account_id %></td>
        <td><%= account_history.amount %></td>
        <td><%= link_to 'Show', account_history %></td>
        <td><%= link_to 'Edit', edit_account_history_path(account_history) %></td>
        <td><%= link_to 'Destroy', account_history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account history', new_account_history_path %>

app/views/account_histories/new.html.erb
<h1>New Account History</h1>

<%= render 'form' %>

<%= link_to 'Back', account_histories_path %>

app/views/account_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @account_history.account_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @account_history.amount %>
</p>

<%= link_to 'Edit', edit_account_history_path(@account_history) %> |
<%= link_to 'Back', account_histories_path %>